import React, { useState } from 'react';
import { useStore, type MapCondition } from '../store/store';

const ConfigPanel: React.FC = () => {
  const selectedNodeId = useStore((state) => state.selectedNodeId);
  const nodes = useStore((state) => state.nodes);
  const edges = useStore((state) => state.edges);
  const updateNodeData = useStore((state) => state.updateNodeData);
  const nodeMetrics = useStore((state) => state.nodeMetrics);
  const isRunning = useStore((state) => state.isRunning);

  const [copySuccess, setCopySuccess] = useState(false);

  const selectedNode = nodes.find((n) => n.id === selectedNodeId);

  // Helper to format Mbps
  const formatBandwidth = (bps: number | undefined): string => {
    if (bps === undefined) return '0 Mbps';
    if (bps >= 1000) {
      return `${(bps / 1000).toFixed(2)} Gbps`;
    }
    return `${bps.toFixed(1)} Mbps`;
  };

  // Helper to format Packets
  const formatPackets = (pps: number | undefined): string => {
    if (pps === undefined) return '0 pps';
    if (pps >= 1000000) {
      return `${(pps / 1000000).toFixed(1)} Mpps`;
    }
    if (pps >= 1000) {
      return `${(pps / 1000).toFixed(1)} kpps`;
    }
    return `${pps.toFixed(0)} pps`;
  };

  // Generate CLI Command script
  const generateCliScript = (): string => {
    let script = '# ==========================================\n';
    script += '# GIGAMON H-SERIES FLOW MAP CONFIGURATION\n';
    script += '# Generated by Fabric Manager Simulator\n';
    script += '# ==========================================\n\n';

    // 1. Define network ports
    script += '# 1. Configure Network Ports (Inputs)\n';
    const inputNodes = nodes.filter((n) => n.type === 'inputNode');
    inputNodes.forEach((node, idx) => {
      const portNum = `1/1/x${idx + 1}`;
      script += `port ${portNum} type network\n`;
      script += `port ${portNum} alias ${String(node.data.label || '').replace(/\s+/g, '_')}\n`;
    });
    if (inputNodes.length === 0) script += '# No input ports configured\n';
    script += '\n';

    // 2. Configure GigaSMART engines if any
    const gigaSmartNodes = nodes.filter((n) => n.type === 'gigaSmartNode');
    if (gigaSmartNodes.length > 0) {
      script += '# 2. Configure GigaSMART Operations\n';
      gigaSmartNodes.forEach((node, idx) => {
        const gsGroup = `gsgrp_${idx + 1}`;
        const action = node.data?.actionType || 'Deduplication';
        script += `apps giga-smart-group ${gsGroup} port 1/1/g${idx + 1}\n`;
        if (action === 'Deduplication') {
          script += `  de-duplication alias dedup_${idx + 1}\n`;
        } else if (action === 'Packet Slicing') {
          script += `  packet-slicing alias slice_${idx + 1} length 64\n`;
        } else if (action === 'Header Stripping') {
          script += `  header-stripping alias strip_${idx + 1} protocol vxlan\n`;
        }
        script += 'exit\n';
      });
      script += '\n';
    }

    // 3. Define tool ports
    script += '# 3. Configure Tool Ports (Destinations)\n';
    const toolNodes = nodes.filter((n) => n.type === 'toolNode');
    toolNodes.forEach((node, idx) => {
      const portNum = `1/1/t${idx + 1}`;
      script += `port ${portNum} type tool\n`;
      script += `port ${portNum} alias ${String(node.data.label || '').replace(/\s+/g, '_')}\n`;
    });
    if (toolNodes.length === 0) script += '# No tool ports configured\n';
    script += '\n';

    // 4. Configure GigaStream (Load Balancer) Groups
    const lbNodes = nodes.filter((n) => n.type === 'gigaStreamNode');
    if (lbNodes.length > 0) {
      script += '# 4. Configure GigaStream Load Balancing Groups\n';
      lbNodes.forEach((node, idx) => {
        const gsAlias = `gstream_${idx + 1}`;
        // Find connected tools
        const outboundEdges = edges.filter((e) => e.source === node.id);
        const targetTools = outboundEdges.map((e) => {
          const toolIdx = toolNodes.findIndex((tn) => tn.id === e.target);
          return toolIdx !== -1 ? `1/1/t${toolIdx + 1}` : null;
        }).filter(Boolean);
        
        if (targetTools.length > 0) {
          script += `port-group alias ${gsAlias}\n`;
          script += `  port ${targetTools.join(', ')}\n`;
          script += `  hash ${node.data?.algorithm === 'L4 Hash' ? 'ipsrc-ipdst-portsrc-portdst' : 'round-robin'}\n`;
          script += 'exit\n';
        }
      });
      script += '\n';
    }

    // 5. Configure Flow Maps and filters
    script += '# 5. Configure Traffic Flow Maps & Rules\n';
    const mapNodes = nodes.filter((n) => n.type === 'mapNode');
    mapNodes.forEach((mapNode) => {
      const mapAlias = String(mapNode.data.label || '').replace(/\s+/g, '_');
      
      // Find source ports
      const inboundEdges = edges.filter((e) => e.target === mapNode.id);
      const srcPorts = inboundEdges.map((e) => {
        const inputIdx = inputNodes.findIndex((inNode) => inNode.id === e.source);
        return inputIdx !== -1 ? `1/1/x${inputIdx + 1}` : null;
      }).filter(Boolean);

      // Find destinations or next hops
      const outboundEdges = edges.filter((e) => e.source === mapNode.id);
      const destPorts: string[] = [];
      const rules: string[] = [];

      // Helper to trace downstream path of map to compile output ports and rules
      const tracePath = (targetId: string) => {
        const targetNode = nodes.find((n) => n.id === targetId);
        if (!targetNode) return;

        if (targetNode.type === 'toolNode') {
          const tIdx = toolNodes.findIndex((tn) => tn.id === targetNode.id);
          if (tIdx !== -1) destPorts.push(`1/1/t${tIdx + 1}`);
        } 
        else if (targetNode.type === 'gigaStreamNode') {
          const lbIdx = lbNodes.findIndex((lb) => lb.id === targetNode.id);
          if (lbIdx !== -1) destPorts.push(`gstream_${lbIdx + 1}`);
        }
        else if (targetNode.type === 'filterNode') {
          // Add filter rules to map
          if (targetNode.data?.configType === 'VLAN Filter' && targetNode.data?.vlanIds) {
            rules.push(`rule add pass vlan ${targetNode.data.vlanIds}`);
          } else if (targetNode.data?.configType === 'IP Subnet Filter' && targetNode.data?.ipSubnet) {
            rules.push(`rule add pass ipdst ${targetNode.data.ipSubnet}`);
          } else if (targetNode.data?.configType === 'Port Filter' && targetNode.data?.ports) {
            rules.push(`rule add pass portdst ${targetNode.data.ports}`);
          }
          // Trace further downstream
          const subEdges = edges.filter((e) => e.source === targetNode.id);
          subEdges.forEach((se) => tracePath(se.target));
        }
        else if (targetNode.type === 'gigaSmartNode') {
          const gsIdx = gigaSmartNodes.findIndex((gs) => gs.id === targetNode.id);
          if (gsIdx !== -1) {
            destPorts.push(`1/1/g${gsIdx + 1}`); // Routes through GigaSMART port
          }
          const subEdges = edges.filter((e) => e.source === targetNode.id);
          subEdges.forEach((se) => tracePath(se.target));
        }
      };

      outboundEdges.forEach((e) => tracePath(e.target));

      // Append conditions defined directly inside map node
      const conditions = (mapNode.data?.conditions as MapCondition[]) || [];
      conditions.forEach((c) => {
        if (c.value) {
          rules.push(`rule add pass ${c.field} ${c.value}`);
        }
      });

      if (srcPorts.length > 0 && destPorts.length > 0) {
        script += `map alias ${mapAlias}\n`;
        script += `  type regular\n`;
        script += `  from ${srcPorts.join(', ')}\n`;
        script += `  to ${destPorts.join(', ')}\n`;
        rules.forEach((rule) => {
          script += `  ${rule}\n`;
        });
        script += 'exit\n';
      }
    });

    if (mapNodes.length === 0) script += '# No traffic maps configured\n';
    
    return script;
  };

  const handleCopyCli = () => {
    navigator.clipboard.writeText(generateCliScript());
    setCopySuccess(true);
    setTimeout(() => setCopySuccess(false), 2000);
  };

  // Calculate global stats when no node is selected
  const getGlobalStats = () => {
    let totalIngest = 0;
    let totalDrops = 0;
    let totalEgress = 0;

    nodes.forEach((n) => {
      const metric = nodeMetrics[n.id];
      if (!metric) return;
      if (n.type === 'inputNode') {
        totalIngest += metric.txBps;
      }
      if (n.type === 'toolNode') {
        totalEgress += metric.rxBps;
      }
      totalDrops += metric.droppedPackets;
    });

    return { totalIngest, totalDrops, totalEgress };
  };

  const globalStats = getGlobalStats();

  // If no node is selected, render Dashboard & CLI Generator
  if (!selectedNodeId || !selectedNode) {
    return (
      <aside className="config-panel">
        <h2>Global Dashboard</h2>
        
        {isRunning ? (
          <div>
            <h3>Active Metrics</h3>
            <div className="metric-grid">
              <div className="form-group">
                <label>Total Ingest</label>
                <div style={{ padding: '8px', background: 'rgba(76, 175, 80, 0.1)', borderRadius: '4px', border: '1px solid rgba(76, 175, 80, 0.2)', fontSize: '13px', fontWeight: 'bold', color: 'var(--color-input)' }}>
                  {formatBandwidth(globalStats.totalIngest)}
                </div>
              </div>
              <div className="form-group">
                <label>Total Delivered</label>
                <div style={{ padding: '8px', background: 'rgba(0, 229, 255, 0.1)', borderRadius: '4px', border: '1px solid rgba(0, 229, 255, 0.2)', fontSize: '13px', fontWeight: 'bold', color: 'var(--color-gigasmart)' }}>
                  {formatBandwidth(globalStats.totalEgress)}
                </div>
              </div>
            </div>
            <div style={{ marginTop: '10px' }} className="form-group">
              <label>Dropped Traffic</label>
              <div style={{ padding: '8px', background: 'rgba(239, 83, 80, 0.1)', borderRadius: '4px', border: '1px solid rgba(239, 83, 80, 0.2)', fontSize: '13px', fontWeight: 'bold', color: '#ef5350' }}>
                {formatBandwidth(globalStats.totalDrops)}
              </div>
            </div>
          </div>
        ) : (
          <div style={{ padding: '12px', background: 'rgba(255,255,255,0.02)', borderRadius: '6px', border: '1px dashed var(--border-color)', fontSize: '12px', color: 'var(--text-secondary)' }}>
            Start the simulation in the header to view active bandwidth graphs and metrics.
          </div>
        )}

        <div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
            <h3 style={{ margin: 0 }}>Gigamon CLI Script</h3>
            <button className="primary" style={{ padding: '4px 8px', fontSize: '11px' }} onClick={handleCopyCli}>
              {copySuccess ? 'Copied!' : 'Copy CLI'}
            </button>
          </div>
          <textarea
            readOnly
            value={generateCliScript()}
            style={{ width: '100%', height: '350px', backgroundColor: 'var(--bg-primary)', color: '#00e5ff', border: '1px solid var(--border-color)', borderRadius: '6px', fontSize: '11px', fontFamily: 'monospace', padding: '10px', whiteSpace: 'pre', resize: 'none' }}
          />
        </div>
      </aside>
    );
  }

  // Selected node values
  const configType = (selectedNode.data?.configType as string) || (selectedNode.data?.label as string);
  const selectedNodeMetric = nodeMetrics[selectedNode.id];

  const mapCriteria = [
    { key: 'vlan', label: 'VLAN ID', placeholder: 'e.g. 100' },
    { key: 'protocol', label: 'IP Protocol', placeholder: 'e.g. tcp, udp, icmp' },
    { key: 'portdst', label: 'Destination Port', placeholder: 'e.g. 80, 443' },
    { key: 'portsrc', label: 'Source Port', placeholder: 'e.g. 1024..65535' },
    { key: 'ipdst', label: 'Destination IPv4', placeholder: 'e.g. 192.168.1.0/24' },
    { key: 'ipsrc', label: 'Source IPv4', placeholder: 'e.g. 10.0.0.5' },
  ];

  const handleLabelChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    updateNodeData(selectedNodeId, { label: e.target.value });
  };

  const handleGenericChange = (key: string, val: string) => {
    updateNodeData(selectedNodeId, { [key]: val });
  };

  // Map node condition handlers
  const handleAddCondition = () => {
    const conditions = (selectedNode.data?.conditions as MapCondition[]) || [];
    updateNodeData(selectedNodeId, { conditions: [...conditions, { logic: 'AND', field: 'vlan', value: '' }] });
  };

  const handleConditionChange = (index: number, key: string, value: string) => {
    const conditions = [...((selectedNode.data?.conditions as MapCondition[]) || [])];
    conditions[index] = { ...conditions[index], [key]: value };
    updateNodeData(selectedNodeId, { conditions });
  };

  const handleRemoveCondition = (index: number) => {
    const conditions = [...((selectedNode.data?.conditions as MapCondition[]) || [])];
    conditions.splice(index, 1);
    updateNodeData(selectedNodeId, { conditions });
  };

  return (
    <aside className="config-panel">
      <h2>Edit Node Configuration</h2>
      
      <div className="form-group">
        <label>Node Label</label>
        <input
          type="text"
          value={(selectedNode.data?.label as string) || ''}
          onChange={handleLabelChange}
        />
      </div>

      {/* VLAN Filter specific properties */}
      {configType === 'VLAN Filter' && (
        <div className="form-group">
          <label>Filter VLAN IDs</label>
          <input
            type="text"
            placeholder="e.g. 100, 200"
            value={(selectedNode.data?.vlanIds as string) || ''}
            onChange={(e) => handleGenericChange('vlanIds', e.target.value)}
          />
        </div>
      )}

      {/* IP Filter specific properties */}
      {configType === 'IP Subnet Filter' && (
        <div className="form-group">
          <label>Filter IP Subnet</label>
          <input
            type="text"
            placeholder="e.g. 192.168.1.0/24"
            value={(selectedNode.data?.ipSubnet as string) || ''}
            onChange={(e) => handleGenericChange('ipSubnet', e.target.value)}
          />
        </div>
      )}

      {/* Port Filter specific properties */}
      {configType === 'Port Filter' && (
        <div className="form-group">
          <label>Filter Destination Ports</label>
          <input
            type="text"
            placeholder="e.g. 80, 443"
            value={(selectedNode.data?.ports as string) || ''}
            onChange={(e) => handleGenericChange('ports', e.target.value)}
          />
        </div>
      )}

      {/* GigaStream Load Balancer specific properties */}
      {selectedNode.type === 'gigaStreamNode' && (
        <div className="form-group">
          <label>Load Balancing Algorithm</label>
          <select
            value={(selectedNode.data?.algorithm as string) || 'Round Robin'}
            onChange={(e) => handleGenericChange('algorithm', e.target.value)}
          >
            <option value="Round Robin">Round Robin (Even Split)</option>
            <option value="L4 Hash">L4 Hash (Five-Tuple hash)</option>
          </select>
        </div>
      )}

      {/* GigaSMART specific properties */}
      {selectedNode.type === 'gigaSmartNode' && (
        <div className="form-group">
          <label>GigaSMART Engine Operation</label>
          <select
            value={(selectedNode.data?.actionType as string) || 'Deduplication'}
            onChange={(e) => handleGenericChange('actionType', e.target.value)}
          >
            <option value="Deduplication">Packet Deduplication</option>
            <option value="Packet Slicing">Packet Slicing (Truncate Payload)</option>
            <option value="Header Stripping">Header Stripping (VXLAN/MPLS)</option>
          </select>
        </div>
      )}

      {/* Traffic Map condition builder */}
      {configType === 'Traffic Map' && (
        <div>
          <h3>Map Criteria (OR-rules list)</h3>
          {((selectedNode.data?.conditions as MapCondition[]) || []).map((condition, index) => (
            <div key={index} className="condition-card">
              <div className="condition-card-row">
                {index > 0 && (
                  <select
                    value={condition.logic}
                    onChange={(e) => handleConditionChange(index, 'logic', e.target.value)}
                    style={{ flex: '0 0 65px', padding: '4px' }}
                  >
                    <option value="AND">AND</option>
                    <option value="OR">OR</option>
                  </select>
                )}
                <select
                  value={condition.field}
                  onChange={(e) => handleConditionChange(index, 'field', e.target.value)}
                  style={{ flex: 1, padding: '4px' }}
                >
                  {mapCriteria.map((c) => (
                    <option key={c.key} value={c.key}>{c.label}</option>
                  ))}
                </select>
                <button className="danger" onClick={() => handleRemoveCondition(index)} style={{ padding: '4px 8px' }}>
                  Remove
                </button>
              </div>
              <input
                type="text"
                placeholder={mapCriteria.find(c => c.key === condition.field)?.placeholder || ''}
                value={condition.value}
                onChange={(e) => handleConditionChange(index, 'value', e.target.value)}
              />
            </div>
          ))}
          <button className="secondary" onClick={handleAddCondition} style={{ width: '100%', marginTop: '5px' }}>
            + Add Match Condition
          </button>
        </div>
      )}

      {/* Node Metrics Section */}
      {isRunning && selectedNodeMetric && (
        <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '15px', marginTop: '10px' }}>
          <h3>Live Node Statistics</h3>
          <div className="form-group" style={{ gap: '8px' }}>
            {selectedNode.type !== 'inputNode' && (
              <div className="metric-badge">
                <span className="label">Rx Throughput:</span>
                <span className="value">{formatBandwidth(selectedNodeMetric.rxBps)}</span>
              </div>
            )}
            {selectedNode.type !== 'inputNode' && (
              <div className="metric-badge">
                <span className="label">Rx Packet Rate:</span>
                <span className="value">{formatPackets(selectedNodeMetric.rxPackets)}</span>
              </div>
            )}
            {selectedNode.type !== 'toolNode' && (
              <div className="metric-badge">
                <span className="label">Tx Throughput:</span>
                <span className="value" style={{ color: 'var(--color-input)' }}>
                  {formatBandwidth(selectedNodeMetric.txBps)}
                </span>
              </div>
            )}
            {selectedNode.type !== 'toolNode' && (
              <div className="metric-badge">
                <span className="label">Tx Packet Rate:</span>
                <span className="value" style={{ color: 'var(--color-input)' }}>
                  {formatPackets(selectedNodeMetric.txPackets)}
                </span>
              </div>
            )}
            {(selectedNodeMetric.droppedPackets > 0 || selectedNode.type === 'filterNode') && (
              <div className="metric-badge">
                <span className="label">Dropped Traffic:</span>
                <span className="value" style={{ color: '#ef5350' }}>
                  {formatBandwidth(selectedNodeMetric.droppedPackets)}
                </span>
              </div>
            )}
          </div>
        </div>
      )}
    </aside>
  );
};

export default ConfigPanel;